name: module3_task1
on:
  push:
  schedule:
    - cron: '10 10 * * *'
jobs:
  building:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo module3_task1/setup.sh
      - run: cd module3_task0 && make build
